name: new_standred
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.4.0+2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.12
  get: ^4.6.6
  get_it: ^8.0.1
  hexcolor: ^3.0.1
  http: ^1.2.2
  image_picker: ^0.8.7+4
  internet_connection_checker: ^1.0.0+1
  intl_phone_field: ^3.2.0
  loading_indicator: ^3.1.1
  painter: ^2.0.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  retry: ^3.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: DGAgnadeen
      fonts:
        - asset: assets/fonts/DGAgnadeen-Thin.ttf
          weight: 100
        - asset: assets/fonts/DGAgnadeen-Ultralight.ttf
          weight: 200
        - asset: assets/fonts/DGAgnadeen-Light.ttf
          weight: 300
        - asset: assets/fonts/DGAgnadeen-Regular.ttf
          weight: 400
        - asset: assets/fonts/DGAgnadeen-Bold.ttf
          weight: 700
        - asset: assets/fonts/DGAgnadeen-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/DGAgnadeen-Heavy.ttf
          weight: 900

